# Generated by Django 5.2.8 on 2025-11-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('image_path', models.CharField(max_length=127)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=511)),
                ('ratings', models.IntegerField(choices=[(0, 'Pending'), (1, 'Very Bad'), (2, 'Bad'), (3, 'Useable'), (4, 'Good'), (5, 'Very Good')], default=0)),
                ('review_comment', models.CharField(max_length=511)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
